services:
  airflow-webserver:
    image: apache/airflow:2.8.4-python3.10
    container_name: airflow-webserver
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
      AIRFLOW__CORE__DAGS_FOLDER: "/opt/airflow/dags"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "sqlite:////opt/airflow/airflow.db"
      _PIP_ADDITIONAL_REQUIREMENTS: "pandas openpyxl pyarrow kafka-python"
    volumes:
      - ../airflow_home/dags:/opt/airflow/dags
      - ../airflow_home:/opt/airflow
      - ..:/project
    command: >
      bash -c "airflow db migrate &&
               airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin || true &&
               exec airflow webserver"

  airflow-scheduler:
    image: apache/airflow:2.8.4-python3.10
    container_name: airflow-scheduler
    restart: unless-stopped
    depends_on:
      - airflow-webserver
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_FOLDER: "/opt/airflow/dags"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "sqlite:////opt/airflow/airflow.db"
      _PIP_ADDITIONAL_REQUIREMENTS: "pandas openpyxl pyarrow kafka-python"
    volumes:
      - ../airflow_home/dags:/opt/airflow/dags
      - ../airflow_home:/opt/airflow
      - ..:/project
    command: >
      bash -c "exec airflow scheduler"
